### ISSUE TITLE
Conflicts within language configurator

### ISSUE THREAD

**Issue by tgalery** [sweble/sweble-wikitext#72]
When using the language configurator to generate a config, we usually get a stacktrace when trying to associate an alias which already has been set, e.g.

```
java.lang.IllegalArgumentException: The name `sub' was already registered by the alias `sub' when trying to register it for alias `img_sub'. at org.sweble.wikitext.engine.config.WikiConfigImpl.addI18nAlias(WikiConfigImpl.java:386) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.addi18NAliases(LanguageConfigGenerator.java:204) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:112) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:78) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:63) at PageBuilder$.apply(PageBuilder.scala:59) at Xml2FasttextDS$.xml2Dataset(Xml2FasttextDS.scala:27) at Xml2FasttextDS$.main(Xml2FasttextDS.scala:139) at Xml2FasttextDS.main(Xml2FasttextDS.scala) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at sbt.Run.invokeMain(Run.scala:67) at sbt.Run.run0(Run.scala:61) at sbt.Run.sbt$Run$$execute$1(Run.scala:51) at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55) at sbt.Run$$anonfun$run$1.apply(Run.scala:55) at sbt.Run$$anonfun$run$1.apply(Run.scala:55) at sbt.Logger$$anon$4.apply(Logger.scala:84) at sbt.TrapExit$App.run(TrapExit.scala:248) at java.lang.Thread.run(Thread.java:745) java.lang.IllegalArgumentException: The name `名前空間:' was already registered by the alias `namespace' when trying to register it for alias `ns'. at org.sweble.wikitext.engine.config.WikiConfigImpl.addI18nAlias(WikiConfigImpl.java:386) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.addi18NAliases(LanguageConfigGenerator.java:204) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:112) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:78) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:63) at PageBuilder$.apply(PageBuilder.scala:59) at Xml2FasttextDS$.xml2Dataset(Xml2FasttextDS.scala:27) at Xml2FasttextDS$.main(Xml2FasttextDS.scala:139) at Xml2FasttextDS.main(Xml2FasttextDS.scala) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at sbt.Run.invokeMain(Run.scala:67) at sbt.Run.run0(Run.scala:61) at sbt.Run.sbt$Run$$execute$1(Run.scala:51) at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55) at sbt.Run$$anonfun$run$1.apply(Run.scala:55) at sbt.Run$$anonfun$run$1.apply(Run.scala:55) at sbt.Logger$$anon$4.apply(Logger.scala:84) at sbt.TrapExit$App.run(TrapExit.scala:248) at java.lang.Thread.run(Thread.java:745) java.lang.IllegalArgumentException: The name `noerror' was already registered by the alias `defaultsort_noerror' when trying to register it for alias `displaytitle_noerror'. at org.sweble.wikitext.engine.config.WikiConfigImpl.addI18nAlias(WikiConfigImpl.java:386) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.addi18NAliases(LanguageConfigGenerator.java:204) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:112) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:78) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:63) at PageBuilder$.apply(PageBuilder.scala:59) at Xml2FasttextDS$.xml2Dataset(Xml2FasttextDS.scala:27) at Xml2FasttextDS$.main(Xml2FasttextDS.scala:139) at Xml2FasttextDS.main(Xml2FasttextDS.scala) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at sbt.Run.invokeMain(Run.scala:67) at sbt.Run.run0(Run.scala:61) at sbt.Run.sbt$Run$$execute$1(Run.scala:51) at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55) at sbt.Run$$anonfun$run$1.apply(Run.scala:55) at sbt.Run$$anonfun$run$1.apply(Run.scala:55) at sbt.Logger$$anon$4.apply(Logger.scala:84) at sbt.TrapExit$App.run(TrapExit.scala:248) at java.lang.Thread.run(Thread.java:745) java.lang.IllegalArgumentException: The name `noreplace' was already registered by the alias `defaultsort_noreplace' when trying to register it for alias `displaytitle_noreplace'. at org.sweble.wikitext.engine.config.WikiConfigImpl.addI18nAlias(WikiConfigImpl.java:386) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.addi18NAliases(LanguageConfigGenerator.java:204) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:112) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:78) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:63) at PageBuilder$.apply(PageBuilder.scala:59) at Xml2FasttextDS$.xml2Dataset(Xml2FasttextDS.scala:27) at Xml2FasttextDS$.main(Xml2FasttextDS.scala:139) at Xml2FasttextDS.main(Xml2FasttextDS.scala) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at sbt.Run.invokeMain(Run.scala:67) at sbt.Run.run0(Run.scala:61) at sbt.Run.sbt$Run$$execute$1(Run.scala:51) at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55) at sbt.Run$$anonfun$run$1.apply(Run.scala:55) at sbt.Run$$anonfun$run$1.apply(Run.scala:55) at sbt.Logger$$anon$4.apply(Logger.scala:84) at sbt.TrapExit$App.run(TrapExit.scala:248) at java.lang.Thread.run(Thread.java:745) java.lang.IllegalArgumentException: No alias registered for parser function `ns'. at org.sweble.wikitext.engine.config.WikiConfigImpl.addParserFunction(WikiConfigImpl.java:449) at org.sweble.wikitext.engine.config.WikiConfigImpl.addParserFunctionGroup(WikiConfigImpl.java:430) at org.sweble.wikitext.engine.utils.DefaultConfig.addParserFunctions(DefaultConfig.java:573) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:114) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:78) at org.sweble.wikitext.engine.utils.LanguageConfigGenerator.generateWikiConfig(LanguageConfigGenerator.java:63) at PageBuilder$.apply(PageBuilder.scala:59) at Xml2FasttextDS$.xml2Dataset(Xml2FasttextDS.scala:27) at Xml2FasttextDS$.main(Xml2FasttextDS.scala:139) at Xml2FasttextDS.main(Xml2FasttextDS.scala) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at sbt.Run.invokeMain(Run.scala:67) at sbt.Run.run0(Run.scala:61) at sbt.Run.sbt$Run$$execute$1(Run.scala:51) at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55) at sbt.Run$$anonfun$run$1.apply(Run.scala:55) at sbt.Run$$anonfun$run$1.apply(Run.scala:55) at sbt.Logger$$anon$4.apply(Logger.scala:84) at sbt.TrapExit$App.run(TrapExit.scala:248) at java.lang.Thread.run(Thread.java:745) [success] Total time: 1 s, completed Jun 8, 2018 11:00:56 AM
```

Now that doesn't mean that the language config is not created, but it seems we would misrepresent some links. This could be related to #5 and appeared in the context of https://github.com/dkpro/dkpro-jwpl/issues/159 . Any pointers with regards to how to move on this would be great.

**Comment by mawiesne** [comment]
Referring to comment in https://github.com/dkpro/dkpro-jwpl/issues/159:

@tgalery Sure, it merely "prints the stacktrace" but it's kind of confusing, e.g for one of my students. Proposal: 

- Print a warning with the exception's message instead of a full stacktrace at LanguageConfigGenerator.java:209? Or even better: 
- Use/introduce a logger that can be configured to be less "alerting" for such a case, so devs can decide what they make out of duplicate keys then?

Cheers
mawiesne

**Comment by tgalery** [comment]
To my mind a warning should suffice. I'm just wondering if there would be a way to allow a many to one relationship so these cases could be covered as well.

**Comment by tgalery** [comment]
So digging more into this issue. Confusing stacktraces aside, it seems that for some languages we are able to create a wikiConfig instance. 

```
import org.sweble.wikitext.engine.utils.LanguageConfigGenerator
val deConfig = LanguageConfigGenerator.generateWikiConfig("de")
deConfig: org.sweble.wikitext.engine.config.WikiConfig = org.sweble.wikitext.engine.config.WikiConfigImpl@e3643ba4
```
This prints a bunch of stacktraces like the one above, but if we do the same thing for `"ja"` pretty much the same stacktraces are produced but no value is created for the config, which is kind of a problem.

**Comment by tgalery** [comment]
@hannesd I've been trying to build this locally, but I'm getting some issues with some of the deps of the project:

```
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project org.sweble:sweble-parent:3.1.7-SNAPSHOT (/Users/thiago/code/tgalery/sweble-wikitext/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM for org.sweble:sweble-parent:3.1.7-SNAPSHOT: Could not transfer artifact de.fau.cs.osr:tooling:pom:3.0.9-SNAPSHOT from/to osr-public-repo (http://mojo-maven.cs.fau.de/content/repositories/public): sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: timestamp check failed and 'parent.relativePath' points at wrong local POM @ line 23, column 10: NotAfter: Wed Jul 25 13:29:37 BST 2018 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

Any pointers ?

**Comment by hannesd** [comment]
I'm sorry but we screwed up and now our certificates have expired. If you turn of certificate validation it should work again but this is of course not ideal: https://stackoverflow.com/questions/21252800/how-to-tell-maven-to-disregard-ssl-errors-and-trusting-all-certs

We'll try to renew our certificates as soon as possible.

**Comment by hannesd** [comment]
Concerning the actual problem with this issue: I'm quite busy at the moment and will not have the time to work on this. If you could provide a pull request I'd be more than happy to accept it. Simply turning the exception into a warning is fine with me, if this solves your problem.

**Comment by hannesd** [comment]
Certificates have been fixed. Sorry for the inconvenience :(

**Comment by tgalery** [comment]
Many thanks for this, will try to come up with a PR as soon as I have the
time.

**Comment by tgalery** [comment]
Sorry @hannesd I've actually tried building using `mvn package install` and I still get the errors. I've tried to use the mvn cli opts in the stack overflow link you mentioned but also without sucess. I'm wondering whether there' s a problem deeper then certificates updates.
Could you try building this locally ?

**Comment by tgalery** [comment]
fyi, I'm trying to build the dev branch, which I think is the base.

**Comment by hannesd** [comment]
Sorry again, the certificate chain had changed and I didn't notice. Should work now...

**Comment by mawiesne** [comment]
@hannesd 
> Simply turning the exception into a warning is fine with me, if this solves your problem.

^ This at least solve spammed consoles which irritate most devs most of the time 👍. @tgalery Can you check `LanguageConfigGenerator.java:209` and fix this odd behaviour? 

Yet, this is merely an optical cure of the underlying problem, I guess.

**Comment by sweble** [comment]
I'm currently on vacation. I'll come back to you in two weeks.

Cheers,
Hannes

**Comment by tgalery** [comment]
@mawiesne just back from a trip today, will have a look today

**Comment by tgalery** [comment]
ok, so dig some digging and kind of understand what's going on. Here is some debug on a branch of mine. From the scala console, we get something like this:

```
scala> val lang = "ja"
scala> val config = LanguageConfigGenerator.generateWikiConfig(lang)
Got: The name `名前空間:' was already registered by the alias `namespace' when trying to register it for alias `ns'. when adding alias ns
java.lang.IllegalArgumentException: No alias registered for parser function `ns'.
  at org.sweble.wikitext.engine.config.WikiConfigImpl.addParserFunction(WikiConfigImpl.java:449)
```

So in the `LanguageConfigurator.java`, `generateWikiConfig`  first tries to run `addi18NAliases` which fails to register the `ns` namespace due to the fact that some other japanese magical word is registered with the keyword `namespace`, but then `addParserFunctions` expects that something is associated with the keyword `ns` and since no exception is handled, a language conf is not created.
One option is to associate multiple keywords with an alias, e.g. `namespace` to be associated with `[ns, 名前空間]`. Does anyone see a problem with that ?

**Comment by tgalery** [comment]
Would be nice to have thoughts on the PR above ^
